dataloader_conf:
    num_workers: 4
    pin_memory: True
    prefetch_factor: 8
    drop_last: False

cv_dataloader_conf:
    num_workers: 2
    pin_memory: True
    prefetch_factor: 4
    drop_last: False

dataset_conf:
    filter_conf:
        max_length: 30 # 音频最大长度/s
        min_length: 0.1
        token_max_length: 448 # token最大长度
        token_min_length: 1
    resample_conf:
        resample_rate: 16000
    speed_perturb: true
    spec_aug: true
    spec_aug_conf:
        num_t_mask: 2
        num_f_mask: 2
        max_t: 50
        max_f: 10
    spec_sub: true
    spec_sub_conf:
        num_t_sub: 3
        max_t: 30
    shuffle: true
    shuffle_conf:
        shuffle_size: 1500
    sort: true
    sort_conf:
        sort_size: 500  # sort_size should be less than shuffle_size
    batch_conf:
        batch_type: 'dynamic' # static or dynamic
        batch_size: 4 # for static
        max_tokens_in_batch: 80 # for dynamic

train_conf:
    use_amp: False
    fp16_grad_sync: False
    grad_clip: 5
    accum_grad: 1
    max_epoch: 360
    max_step: 10000
    log_interval: 20
    step_save_interval: 200
    epoch_save_interval: 1

optim: adam # adam or adamw
optim_conf:
    lr: 0.001
scheduler: warmuplr     # warmuplr or NoamHoldAnnealing
scheduler_conf:
    warmup_steps: 25000
